id: PDD355ABA
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Tenpe Nyima Series
  language: pt
  description: 'Texts by and about the Third Dodrupchen, Jigme Tenpe Nyima (rdo grub
    chen ''jigs med bstan pa''i nyi ma, 1865–1926):'
  volume:
    0d6daeac3dda4671a9bf9a721d24a301:
      title: Advice for a Dying Practitioner
      parent: Advice
    f49e9ea8ef744567a4c619fa743eb22e:
      title: On Seeing the Guru as a Buddha
      parent: Advice
    87cdc17481ab47539f0a19512f10c819:
      title: On Sleep
      parent: Advice
    ee24604fa1c743ba88d02356afe24849:
      title: On the Ignorance of the Learned
      parent: Advice
    888f4ffe7ec5475987ada7231d9f0084:
      title: Retreat Advice
      parent: Advice
    96880f362a9a42518fe509127ee4d788:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    dbd9252ac93a4246b9c3249db077c561:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Advice
    377c8122bf7a4eb6baa4d9170f210f7d:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers
    5fa3827f3da74ca7bcf15b71d8c390d1:
      title: Aspirations in Accordance with the Dharma
      parent: Aspiration Prayers
    ce0fc2d9fcf64893a3ca78dcb1fd396a:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    27a1fd9b6fc14d699cfbf36264a23f93:
      title: A Simple Visualization for the Seven-Line Prayer
      parent: Commentaries
    67caffd6fb3e49fc808af6109cc63312:
      title: 'Garland of Night-Blooming Water Lilies: A Commentary on the Guru Siddhi
        Mantra'
      parent: Commentaries
    ae2d0aa2e81e4a29830a59fbd4d6eb7e:
      title: 'Lamp That Illuminates the Excellent Path of Great Bliss: A Guide to
        the Practice Text of the Female Awareness-Holder, the Queen of Great Bliss'
      parent: Commentaries
    ac7d052f88ad4dca83f6e367171802d2:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    cf96da6ef75f4cd2abec5c7bf77533ba:
      title: Teaching on the Offering of Flowers
      parent: Commentaries
    d023749db47940749fd41a651ead2bb3:
      title: Advice for Hor Özer
      parent: Dzogchen
    825a7e427ffd49c0a35004e415852fd4:
      title: Advice for Palseng
      parent: Dzogchen
    434ac3545d7f4393880fc0f16fe514b1:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Dzogchen
    3b449d3f7af94dfc8f5229ab4c6d1af7:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    e36758739a02493bba295cbd07fcfd25:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    a8f6df19edfd4353afc8a81508b111f0:
      title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
      parent: Lineage Prayers
    8da98b024a5e48998aa24691e223fa22:
      title: A Brief Ritual for Consecrating Representations of Enlightened Body,
        Speech and Mind
      parent: Practices
    49094f7e872a4e0b9d7e5d5f39edee69:
      title: Rigdzin Düpa Amṛta Offering
      parent: Practices
    f474f00d816e4315b165d69f4ea55ba1:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Practices
    d094b51aab9a4fec93a106e7827bf879:
      title: Yumka Fulfilment Practice
      parent: Practices
    188520e1afad41a2a1ef495a0698c3a2:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    4e0db4409130479d95faac8aff4d09d6:
      title: In Praise of Sönam Palge
      parent: Praise
    ae291a7621a24b52baabb7540fd1b202:
      title: Prayer to Ārya Tārā
      parent: Prayers
    44bb9fb58a96462c9e1c95283d9221fe:
      title: Prayer to Avalokiteśvara
      parent: Prayers
    31ab6df472894d2ca727f89c0fe0574b:
      title: Prayer to Buddha Amitābha
      parent: Prayers
    a11bad4aaa5d4ba1beec18ed437625bd:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Prayers
    270a5052660645f7a6f3f02f31e318d4:
      title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
        Female Practice'
      parent: Sādhanas
created_at: '2022-02-28T22:58:39.867261'
last_modified_at: '2022-02-28T22:58:39.867263'
